version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}      
      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"            
      - run:
          name: Running Tests
          command: |
            . venv/bin/activate
            cd ~/Smabuz-Inventory/smabuz
            python3 tests.py 
      - store_artifacts:
          path: test-reports/
          destination: SmaBuz-Inventory       
 

