version: 2.1
jobs:
  build:
    working_directory: ~/Smabuz-Inventory
    docker:
      - image: circleci/python:3.8
    steps:
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}      
      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - checkout:
          path: ~/Smabuz-Inventory/smabuz                       
      - run: 
          name: Running Tests
          command: |
            . venv/bin/activate
            python3 test.py
    
 

