"""add Users.google_id

Revision ID: 644004fa72dd
Revises: 60e20547afcc
Create Date: 2024-06-02 20:54:24.264417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644004fa72dd'
down_revision = '60e20547afcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
