"""removed UserRoles

Revision ID: 824421776417
Revises: 
Create Date: 2024-06-02 16:51:43.356219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824421776417'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_role_id_fkey', type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('users_role_id_fkey', 'user_roles', ['role_id'], ['id'])

    # ### end Alembic commands ###
