"""remove rel

Revision ID: c71f9b129e8c
Revises: 644004fa72dd
Create Date: 2024-06-12 07:24:51.094314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71f9b129e8c'
down_revision = '644004fa72dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_product_id_fkey', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('products_product_id_fkey', 'users', ['product_id'], ['id'])

    # ### end Alembic commands ###
